### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by PRAVESH-RATHEE** [lyxok1/Tiny-DSOD#26]
the video detection module of Tiny-DSOD fails first gives below error:
 
Traceback (most recent call last):
File "examples/DCOD/video_detection_demo.py", line 198, in
fps = (batch_size*len(batch_list))/total_time
ZeroDivisionError: float division by zero

When the total_time value is set equal to time of video I get below error:
I0616 17:45:29.350755 10882 net.cpp:781] Ignoring source layer mbox_loss

(python:10882): GLib-GObject-CRITICAL **: g_object_set: assertion 'G_IS_OBJECT (object)' failed
finish reading videos...
Traceback (most recent call last):
  File "examples/DCOD/iith_video_detection_demo.py", line 205, in <module>
    output_size = (output[0].shape[0], output[0].shape[1])
IndexError: list index out of range

Can you help how to proceed for video detection.

**Comment by QingxinWx** [comment]
meet the same error
