### ISSUE TITLE
Total_time doesn`t increase in video_detection_demo.py

### ISSUE THREAD

**Issue by FelixCaae** [lyxok1/Tiny-DSOD#8]
finish processing batch 74
finish processing batch 75
finish processing batch 76
Traceback (most recent call last):
  File "examples/DCOD/video_detection_demo.py", line 198, in <module>
    fps = (batch_size*len(batch_list))/total_time
ZeroDivisionError: float division by zero

**Comment by PRAVESH-RATHEE** [comment]
#Load image.
    video_dir = args.video
    
    total_time = 0.0

    batch_list = []

enter the time of your video in seconds at total_time . this resolved my error.]
Although faced another error:
 File "examples/DCOD/it_video_detection_demo.py", line 205, in <module>
    output_size = (output[0].shape[0], output[0].shape[1])
IndexError: list index out of range

**Comment by QingxinWx** [comment]
> #Load image.
> video_dir = args.video
> 
> ```
> total_time = 0.0
> 
> batch_list = []
> ```
> 
> enter the time of your video in seconds at total_time . this resolved my error.]
> Although faced another error:
> File "examples/DCOD/it_video_detection_demo.py", line 205, in 
> output_size = (output[0].shape[0], output[0].shape[1])
> IndexError: list index out of range

how do you resolved this error?
